name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/creavo-master
          docker build . --file Dockerfile --tag $IMAGE_NAME:latest --tag master:${{ github.sha }}

      - name: Push the Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/creavo-master
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
